### ISSUE TITLE
Add Youtube in About

### ISSUE THREAD

**Issue by morrigan** [KSET/jobfair-mobile#17]
Originally reported by: **belma (Bitbucket: [belma](https://bitbucket.org/belma), GitHub: [belma](https://github.com/belma))**

----------------------------------------

+ increment version and publish

----------------------------------------
- Bitbucket: https://bitbucket.org/belma/extensions/issue/17

**Comment by mpetrunic** [comment]
@morrigan closed?

**Comment by mpetrunic** [comment]
Ovo nije gotovo
