### ISSUE TITLE
Data (lazy) loading

### ISSUE THREAD

**Issue by morrigan** [KSET/jobfair-mobile#3]
Originally reported by: **belma (Bitbucket: [belma](https://bitbucket.org/belma), GitHub: [belma](https://github.com/belma))**

----------------------------------------

- Presentations stop loading after INETEC
- Companies at some point too

----------------------------------------
- Bitbucket: https://bitbucket.org/belma/extensions/issue/3

**Comment by mpetrunic** [comment]
Solved problem by contributing to shoutem/redux-io
